name: instagram_clone
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.5.0-dev.68.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2
  flutter_fortune_wheel: 
  flutter_spinning_wheel :
  animated_check: ^1.0.5
  flutter_countdown_timer:
  flutter_shake_animated: 
  storage_path: 0.2.0
  transparent_image: 1.0.0
  scrollable_positioned_list: 0.1.8
  google_sign_in:
  firebase_auth: 
  cloud_firestore: 
  firebase_core: 
  rxdart: 
  image_picker: 0.6.0
  file_picker: 
  firebase_storage: 4.0.1
  cached_network_image: 2.5.1
  provider: 4.0.1
  image:
  animator: 2.0.0
  flutter_svg: 0.19.3
  path_provider: 1.6.24
  image_gallery: 1.2.0
  image_crop: 0.3.4
  media_gallery: 0.1.5
  fluttertoast: 7.1.5
  flutter_image_compress: ^0.7.0
  flushbar: 1.10.4
  flutter_cache_manager: 2.1.0
  progressive_image: 1.0.1
  photo_manager: 1.0.0
  image_size_getter: 0.2.1
  confirm_dialog: 0.1.1
  progress_indicators: ^1.0.0
  carousel_slider: 2.3.0
  infinite_scroll_pagination: 3.0.0
  timeago: 
  dotted_border: 


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#    - assets/insta_logo.png
#    - assets/insta_logo.png
    - lib/static/images/  
    - lib/static/backgrounds/
    - lib/static/cards/
    - assets/google_icon.jpg
    - assets/profile_background.png
    - assets/Alexis-Sanchez.png
    - assets/Paul-Pogba.png
    - assets/Christiano-Ronaldo.png
    - assets/Lionel-Messi.png
    - assets/asyiz.png
    - assets/asyiz-removed.png
    - assets/asyiz-transparent.png
    - assets/game_play.png
    - assets/search.svg
    - assets/grey.png
    - assets/lobby.png
    - assets/profile_pic1.png
    - assets/profile_pic2.png
    - assets/profile_pic3.png
    - assets/profile_pic4.png
    - assets/general_background.png
    - assets/Sadio-Mane.png
    - assets/Mohammed-Salah.png
    - assets/Karim-Benzema.png
    - assets/Luca-Modric.png
    - assets/Bukayo-Saka.png
    - assets/Kylian-Mbappe.png
    - assets/football1.png
    - assets/football2.jpg
    - assets/football3.jpg
    - assets/football4.jpg
    - assets/wallpaper.png
    - assets/stadium.png
    - assets/no_image.jpg
    - assets/group.jpg
    - assets/solo.jpg
   


  fonts:
    - family: MyFlutterApp
      fonts:
      - asset: lib/fonts/MyFlutterApp.ttf
      - asset: lib/fonts/Helvetica.ttf

    - family: MaturaFont
      fonts:
       - asset: assets/MATURASC.TTF

    - family: Muli
      fonts:
       - asset: assets/Muli-Regular.TTF
       - asset: assets/Muli-SemiBold.TTF


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
